#include "Games.h"

const GameEntry GAME_LIBRARY[] = {
  {"Pong", "Arcade", runPong},
  {"Snake", "Arcade", runSnake},
  {"Full Speed", "Racing", runFullSpeed},
  {"Lunar Module", "Skill", runLunarModule},
  {"Breakout", "Arcade", runBreakout},
  {"Flappy Pico", "Arcade", runFlappyPico},
  {"Dino Runner", "Arcade", runDinoRunner},
  {"Jetpack", "Arcade", runJetpackRunner},
  {"Dodge Rain", "Arcade", runDodgeRain},
  {"Catch Star", "Arcade", runCatchStar},
  {"Basket Catch", "Arcade", runBasketCatch},
  {"Balloon Pop", "Arcade", runBalloonPop},
  {"Cave Flyer", "Arcade", runCaveFlyer},
  {"Tunnel Run", "Arcade", runTunnelRunner},
  {"Wall Bounce", "Arcade", runWallBounce},
  {"Gravity Flip", "Arcade", runGravityFlip},
  {"Platform Hop", "Arcade", runPlatformHopper},
  {"Brick Drop", "Arcade", runBrickDrop},
  {"Lane Racer", "Motion", runLaneRacer},
  {"Traffic Dodge", "Motion", runTrafficDodge},
  {"Ski Slalom", "Motion", runSkiSlalom},
  {"Boat Slalom", "Motion", runBoatSlalom},
  {"Rail Runner", "Motion", runRailRunner},
  {"Road Drift", "Motion", runRoadDrift},
  {"Asteroids", "Shooter", runAsteroidsLite},
  {"Invaders", "Shooter", runInvadersLite},
  {"Missile Cmd", "Shooter", runMissileCommandLite},
  {"Turret Def", "Shooter", runTurretDefense},
  {"UFO Defender", "Shooter", runUfoDefender},
  {"Meteor Blast", "Shooter", runMeteorBlaster},
  {"Lights Out", "Puzzle", runLightsOut},
  {"Minefield", "Puzzle", runMinefield},
  {"Sokoban", "Puzzle", runSokobanMicro},
  {"Sliding", "Puzzle", runSlidingPuzzle},
  {"Memory", "Puzzle", runMemoryMatch},
  {"Simon", "Puzzle", runSimon},
  {"Mastermind", "Puzzle", runMastermind},
  {"Number Guess", "Puzzle", runNumberGuess},
  {"Flood Fill", "Puzzle", runFloodFill},
  {"Box Push", "Puzzle", runBoxPush},
  {"Laser Mirror", "Puzzle", runLaserMirror},
  {"Tic Tac Toe", "Board", runTicTacToe},
  {"Connect Four", "Board", runConnectFour},
  {"Nim", "Board", runNim},
  {"Dots Boxes", "Board", runDotsBoxesLite},
  {"Reaction", "Reflex", runReactionTimer},
  {"Quick Draw", "Reflex", runQuickDraw},
  {"Stop Bar", "Reflex", runStopTheBar},
  {"Stack Tower", "Reflex", runStackTower},
  {"Lock Pick", "Reflex", runLockPick},
  {"Pixel Whack", "Reflex", runPixelWhack},
  {"Pulse Match", "Reflex", runPulseMatch}
};

const uint8_t GAME_COUNT = sizeof(GAME_LIBRARY) / sizeof(GAME_LIBRARY[0]);
